#设置启用的环境
spring:
  profiles:
    active: dev
---
#开发
spring:
  config:
    activate:
      on-profile: dev
server:
  port: 8080

---
#生产
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 8081

---
#测试
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082
